// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sun Dec 23 19:42:35 2018

BeginLine BeginLine_inst
(
	.DisLine(DisLine_sig) ,	// input [0:479] DisLine_sig
	.FallLine(FallLine_sig) ,	// output [0:479] FallLine_sig
	.start(start_sig) ,	// output  start_sig
	.level(level_sig) ,	// output [2:0] level_sig
	.clk(clk_sig) ,	// input  clk_sig
	.Ascii(Ascii_sig) ,	// input [7:0] Ascii_sig
	.h_addr(h_addr_sig) ,	// input [9:0] h_addr_sig
	.ready(ready_sig) 	// output  ready_sig
);

