// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Thu Dec 13 21:31:09 2018

random_le random_le_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.h_addr(h_addr_sig) ,	// output [9:0] h_addr_sig
	.font(font_sig) 	// output [143:0] font_sig
);

defparam random_le_inst.a = 30;
defparam random_le_inst.b = 200;
